### ISSUE TITLE
Template error on New Node form

### ISSUE THREAD

**Issue by superwick** [fromtheoutfit/navee#1]
When trying to add my first new node in my fresh navigation, i get the following template error:

```
Variable "event" does not exist
/etc/www/sample-project/craft/plugins/navee/templates/nodes/_edit.html(17)
```

The offending line:

```
17   {% if craft.isLocalized() %}<input type="hidden" name="locale" value="{{ event.locale }}">{% endif %}
```

**Comment by michaelfromtheoutfit** [comment]
Hey @superwick - Just pushed up a change. Can you give that a shot?

**Comment by superwick** [comment]
Yup. Good to go. Thanks!

**Comment by michaelfromtheoutfit** [comment]
Glad to help! Let me know if you run into anything else.
