### ISSUE TITLE
Command + S causes a CP error on save

### ISSUE THREAD

**Issue by theskyfloor** [fromtheoutfit/navee#12]
Saving via the button work fine - using the Craft standard Command + S keyboard command causes and error page.

**Comment by darith27** [comment]
I'm seeing the same error. CMD + S causes the browser to redirect to an unresolved URL in the following format:`domain.com/admin/navee/{navigation_handle}/{navigation_item_id}`, but the entry still goes through just fine.

Clicking the `save` button functions as expected.

**Comment by michaelfromtheoutfit** [comment]
Hey guys,

This one should be resolved up in master. I'm going to bundle it with a bunch of slightly longer burn issues into a release but feel free to pull master now to get the fix.

MW
