### ISSUE TITLE
Feature Request: Allow global craft variables

### ISSUE THREAD

**Issue by mikestecker** [fromtheoutfit/navee#15]
I'd love to put my log in/log out links into my menus by using Craft's global variables.

I've managed to do it manually by adding some light switch toggles to decide whether or not to show a link based off their login state, and I handle it in the template... but I'd like to be able to tie in the `{{ loginUrl }}` and `{{ logoutUrl }}`'s so that it matches what's configured in Craft rather than simply choosing it as a custom link and putting the link in manually.

**Comment by michaelfromtheoutfit** [comment]
Hey @mikestecker I've added this functionality to 1.3.0.
