### ISSUE TITLE
Only output if current page is part of the navigation?

### ISSUE THREAD

**Issue by dylantuohy** [fromtheoutfit/navee#16]
Hi there, I'm giving Navee a try and it's great. I have a question. 

I'm attempting to create a "sidebar" nav which only displays the active branch, using the 'startWithAncestorOfActive' parameter. This works great if the current page _is_ a part of the navigation. 

But it seems that if the current page is not in the navigation, the entire nav tree is output. I'd like for nothing to be output if the current page is not a part of the navigation. Is this possible?

Thanks in advance.

**Comment by michaelfromtheoutfit** [comment]
Hey @dylantuohy - I just pushed up a change 1.0.9 which should fix this issue. Thanks so much for pointing it out!

**Comment by dylantuohy** [comment]
works great. Thanks Michael!
