### ISSUE TITLE
Request: startWithNodeId

### ISSUE THREAD

**Issue by simplethemes** [fromtheoutfit/navee#17]
Hi, I have a situation where the client wants to display the submenus as a sidebar on a entry that doesn't exist in the menu hierarchy. For situations such as this, it'd be nice to implicitly tell navee where to begin.

I tried adding the nodes to the menu and deselecting "Include in navigation" in hopes that it would still see its parents, but no luck there either.

**Comment by michaelfromtheoutfit** [comment]
Hey @simplethemes,

I've added two new parameters: [startWithNodeId](https://github.com/fromtheoutfit/navee/wiki/Parameters#startwithnodeid) and [startWithChildrenOfNodeId](https://github.com/fromtheoutfit/navee/wiki/Parameters#startwithchildrenofnodeid)

I think these should take care of it for you.

MW
