### ISSUE TITLE
Request: Navee Field Type

### ISSUE THREAD

**Issue by spAnser** [fromtheoutfit/navee#18]
A way to select a Navee Navigation to use.

Maybe a way to black list some navigations from the choices.

**Comment by michaelfromtheoutfit** [comment]
Hey @spAnser!

I _think_ you sent me a message while I was away saying that you had coded this up. Is that correct? If so, could you link to the repo here so that other people can find it? Thanks so much!

**Comment by spAnser** [comment]
Ah I didn't put it in a public repo just yet. Will post as soon as I do though.

**Comment by theskyfloor** [comment]
@spAnser did you get this working ever?

**Comment by spAnser** [comment]
I think I made a mini plugin that I hadn't open sourced yet. I can probably look into putting it into a repo in a few days.

**Comment by theskyfloor** [comment]
Cool - should be in Navee IMO - need it often!

**Comment by theskyfloor** [comment]
Even if you could just send it directly to me - I would be greatly appreciative - no pressure but it would be huge for a build that is due this weekend. Thanks!
