### ISSUE TITLE
Issue updating to 1.1.0

### ISSUE THREAD

**Issue by akuzemchak** [fromtheoutfit/navee#19]
**Craft version:** 2.6.2944

While trying to update to Navee 1.1.0, I encountered the following error:

`Fatal error: Class 'Craft\SeomaticPlugin' not found in craft/plugins/navee/migrations/m160922_150924_navee_AddRegexField.php on line 52`

This prevents the migration from being completed for me.

Thanks for your help!

**Comment by michaelfromtheoutfit** [comment]
D'oh! I was using nycstudio107s migration as a blueprint. Forgot to remove a reference. Can you pull it down now and let me know if that fixes it?

Hope all is well man! Long time no see!

**Comment by akuzemchak** [comment]
Works perfectly now... I'd say go ahead and tag 1.1.1! That regex field was something I had been hoping for :)

All is well with me, hoping the same for you!
