### ISSUE TITLE
Navee Fails on Craft Personal

### ISSUE THREAD

**Issue by theskyfloor** [fromtheoutfit/navee#2]
The built in ability to limit Navee nodes by user groups fails on Craft Personal where user groups aren't a thing:

`Impossible to invoke a method ("getAllGroups") on a null variable`

`{% set allGroups = craft.userGroups.getAllGroups() %}`
![screen shot 2016-05-17 at 6 09 53 pm](https://cloud.githubusercontent.com/assets/8887839/15342415/978713ce-1c5a-11e6-80c2-34c680d5522d.png)

**Comment by michaelfromtheoutfit** [comment]
Hey @theskyfloor I'll have a look at this straight away.

**Comment by michaelfromtheoutfit** [comment]
Hey @theskyfloor - I just created a quick personal account and wasn't able to recreate the issue. Is there anything more you can tell me about how you got to this error? Was it immediately when you clicked to create your first node?

Also, which version of Craft are you running? Thanks so much!

**Comment by theskyfloor** [comment]
Odd I thought for sure it must be a Craft Personal issue... 

It was a fresh install of Craft - I still have the install and it is still erring out if you need more information let me know.

Version:  `Craft 2.6.2785`

**Comment by michaelfromtheoutfit** [comment]
Aha! Once I turned on dev mode I was able to recreate it. I'll dig into a fix shortly.

**Comment by michaelfromtheoutfit** [comment]
Hey @theskyfloor - I've pushed up a new version which checks the version first. Can you let me know if that fixes the issue for you? Thanks so much!

**Comment by theskyfloor** [comment]
Fixed!

**Comment by michaelfromtheoutfit** [comment]
![](http://mrwgifs.com/wp-content/uploads/2013/03/Fred-Savage-Thumbs-Up-Reaction-Gif.gif)
