### ISSUE TITLE
Reverse Parameter? Add Class for Has Children?

### ISSUE THREAD

**Issue by brianrivet** [fromtheoutfit/navee#23]
Hi, 

Does Navee for Craft have a reverse parameter like the EE version? I have a nav that is going to float right and I need to reverse the order on output. I don't see anything about it in the docs.

Also, I wanted to add a class to any nav item that has children. I tried to use the ifchildren conditional but I keep getting an error when I do it. Is there some reason it can't be nested in other conditionals?

Thanks!

Brian

**Comment by michaelfromtheoutfit** [comment]
Hey @brianrivet,

I've added the reverseNodes parameter which should take care of the first issue: https://github.com/fromtheoutfit/navee/wiki/Parameters#reverseNodes into version 1.2.0

I've also added a hasChildren variable which should help you get around any nested conditional issues. https://github.com/fromtheoutfit/navee/wiki/Variables#haschildren

MW
