### ISSUE TITLE
Request: allow bypassing default ElementCriteriaModel limit of 100

### ISSUE THREAD

**Issue by superwick** [fromtheoutfit/navee#24]
By default, Craft sets the limit of the ElementCriteriaModel to 100. This can be bypassed by setting the limit parameter to null (or to any number) on lookups. If you have a Navee navigation structure containing more than 100 nodes, only the first 100 notes are returned. This can be resolved by changing line 44 of NaveeService.php to include the limit parameter on the criteria, such as:

```
$criteria             = craft()->elements->getCriteria('Navee_Node')->limit(null);
```

What would be even nicer is a config parameter in Navee to set the limit to any number or null.

**Comment by michaelfromtheoutfit** [comment]
Thank you so much @superwick - this will be added to 1.1.2.
