### ISSUE TITLE
Enhancement: Add field to enter wrapper class via plugin admin interface

### ISSUE THREAD

**Issue by SherriAlexander** [fromtheoutfit/navee#4]
Hey there!  Loving this plugin so far.  :)  The one thing I'd love to see though -- currently, it seems like the only way to use the "class" parameter on the nav wrapper is to use the "roll your own" approach (correct me if I'm wrong here).  That CSS class on the `ul` element is the main customization I actually need when creating most navigations though.  It would be super convenient if there was a way to specify the nav wrapper class on the Add/Edit screen for a navigation, with a "CSS Class" field or similar.  

Thanks for putting this plugin out there, I'll be keeping it in my toolkit for sure!

**Comment by michaelfromtheoutfit** [comment]
Hi @SherriAlexander!

I think the docs might be a little confusing. You can totally pass any/all parameters to the simple method as well. See here: https://github.com/fromtheoutfit/navee/wiki/Tags#simple---craftnaveenav

Hope that helps!

MW

**Comment by SherriAlexander** [comment]
Hey there, Michael!

Hm...that was actually the first thing I'd tried, and it doesn't seem to be working.  Here's the code I'm trying out:

```
{% set navConfig = {
    'maxDepth' : 1,
    'class'    : 'nav nav-simple utilitynav'
} %}

{{ craft.navee.nav('utilityNav', navConfig) }}
```

I'd expected that the generated `ul` tag would have the classes "nav nav-simple utilitynav" on it.  Instead it's just generating a plain `ul` tag, no classes.

Whereas, if I use this code, it works as expected:

```
{% set navConfig = {
    'maxDepth' : 1,
    'class'    : 'nav nav-simple utilitynav'
} %}

{% set navigation = craft.navee.getNav('utilityNav') %}

<ul{% if navConfig.class %} class="{{ navConfig.class }}"{% endif %}>
    {% nav node in navigation %}
        <li{% if node.class %} class="{{ node.class }}"{% endif %}>
            <a href="{{ node.link }}"{% if node.target %} target="{{ node.target }}"{% endif %}>{{ node.title }}</a>
        </li>
    {% endnav %}
</ul>
```

Thoughts?  Let me know if I'm doing something wrong...thanks!

**Comment by michaelfromtheoutfit** [comment]
@SherriAlexander You are absolutely correct - this was a bug. I've fixed it and pushed up a new version that should be working as expected. Sorry about that! :)

**Comment by SherriAlexander** [comment]
It's working like a charm now -- thank you!  :)
