### ISSUE TITLE
Linking to homepage

### ISSUE THREAD

**Issue by roberttolton** [fromtheoutfit/navee#6]
I'm trying to link a node to my homepage, which has the slug of `__home__` in order for Craft to recognise it as the homepage (not using the normal method).

However Navee wants to actually link the node to `http://site.dev/__home__` which of course isn't desired, so I tried just `/`, however while it works there's no real "connection" between the node and the entry.

Thoughts?

**Comment by michaelfromtheoutfit** [comment]
Hey @roberttolton,

Just so I understand - is the issue that you aren't getting the node marked as the active node when using this method? Or is there another issue as well?

MW

**Comment by michaelfromtheoutfit** [comment]
Hey @roberttolton - I can't seem to recreate this one. If I use the custom method for the home node and add "/" as the value - Navee is picking up that I have selected that node and adding the active class as expected. I'm a bit confused.

**Comment by roberttolton** [comment]
Hi @michaelfromtheoutfit sorry, I edited the task after I realised I described it wrongly, the active class does indeed get set correctly, so that's all fine.

The issue now is just that if I create a node with a link to an entry with the slug of `__home__` the URI then prints out with this slug, rather than re-writing it to say, just the site's URL or `/`.

A&M Nav seems to handle this, so I'm not sure what they're doing - maybe worth a look? Cheers!

**Comment by michaelfromtheoutfit** [comment]
Hey @roberttolton,

I'm admittedly relatively new to Craft in general. Can you hip me as to why you'd want to link an entry with the slug of **home** rather than just selecting "Custom" from the link type and typing in the / as the uri?

MW

**Comment by roberttolton** [comment]
Basically, I'm not using a `single` type entry with the "This is the homepage" checkbox checked, and so in order for an entry in a `channel` to be called for the homepage you can use the `__home__` slug, a special slug that Craft recognises and uses for the homepage.

It's not too much of a big deal to just use a custom link of `/` but, you don't get that fancy edit button on the node row to edit the page 😛 

Some background on the slug:
[http://craftcms.stackexchange.com/questions/1467/add-home-page-to-a-structure/5467#5467](url)

**Comment by lyonsrob** [comment]
@roberttolton @michaelfromtheoutfit This might be of some help: 

http://craftcms.stackexchange.com/questions/2603/removing-home-from-home-page-link

**Comment by michaelfromtheoutfit** [comment]
Hey folks,

Finally got around to including this - my apologies for the delay. Should be available in v1.3.0.
