### ISSUE TITLE
"Page Not Found" when creating child nodes

### ISSUE THREAD

**Issue by roberttolton** [fromtheoutfit/navee#7]
I'm getting the following error when selecting a node and trying to create a child node for it:

(Animated GIF below)
![screen recording 2016-06-13 at 04 03 pm](https://cloud.githubusercontent.com/assets/3510875/16012235/82cee016-3180-11e6-9f51-e246e8b4cef6.gif)

**Comment by michaelfromtheoutfit** [comment]
Hey @roberttolton - I've just pushed up a fix to master. Should be all set with this one.

**Comment by roberttolton** [comment]
Perfect, thanks!
